### PR TITLE
Fish support

### PR DESCRIPTION
**Pull request by volkov**
Issue #68 work in progress.

Struck with problem of getting current process cursor position [superuser](https://superuser.com/questions/1390998/fish-commandline-get-cursor-position-in-current-process). 

Also some tests are broken (currently ignored or added to "expected failures").

### CODE REVIEW

**Comment by volkov** [comment]
Well... Local run looks much better. I think I should check travis fish version/installation.

**Comment by volkov** [comment]
@kislyuk Could you please take a look?

I also have to unlock xcode version (may be it should be locked on `xcode 9.4`?) and change `pip install` to `python -m pip install` to pass build.

**Comment by evanunderscore** [comment]
This looks great! I'm not a fish user, but I'd be happy to take a look at this when I can find some spare time (though unfortunately that may not be for a while).

I can at least comment on the xcode problem - I added that line based on the advice in [this issue](https://github.com/travis-ci/travis-ci/issues/8829) because OSX builds were broken. If the builds are working again without it, it's fine to remove.

**Comment by marcoesposito1988** [comment]
This would be a life saver.

Is any help needed?

**Comment by kislyuk** [comment]
Sorry about the delay, didn't notice this was ready for review.

**Comment by kislyuk** [comment]
I don't think we need to configure the OS X build beyond the defaults if it works.

**Comment by kislyuk** [comment]
I'm waiting for tests to pass on master, then I will roll a release.

**Comment by kislyuk** [comment]
Now released in v1.10.0. I'm not an active fish user, so please test this release for me.

@volkov thanks again for your work on this and apologies for the delays here.

**Pull request merged**
