### PR TITLE
Let bash add or suppress trailing space

### LINKED ISSUE #50: zsh escapes space after singleton completions
On unique completion possibilities, a trailing space is added. This has the nice effect of adding a space on the command line, but is not an ideal way to do so. zsh, for instance, is smart enough to notice that trailing space, and keeps escaping it automatically (so instead of '--help', zsh completes it as '--help\ ' which is incorrect).

IMHO, this is better handled by removing the '-o nospace' in:

```
complete -o nospace -o default -F _python_argcomplete "t"
```

...and removing these lines:
#### in **init**.py:

```
 If there's only one completion, and it's not open-quoted and doesn't end with a continuation char, add a space
 continuation_chars = '=/:'
if len(completions) == 1 and completions[0][-1] not in continuation_chars:
    if cword_prequote == '' and not completions[0].endswith(' '):
        completions[0] += ' '
```

Is there any reason not to do so that I'm not seeing?

### PR DESCRIPTION
**Pull request by evanunderscore**
Fixes #50 and #151

### CODE REVIEW

**Comment by evanunderscore** [comment]
I know this may be somewhat controversial since it's a fairly fundamental shift in the interaction between argcomplete and the shell. I'm also not aware of exactly how this will affect shells like zsh or tcsh.

**Comment by kislyuk** [comment]
Thanks for the PR. I think I'm on board with this, but I'm still trying to understand the possible side effects (or lack thereof) of this.

Could you please rebase this on master so it's good to merge?

**Comment by evanunderscore** [comment]
As far as I can tell, there should be no difference when this is used from bash. However this will definitely impact anyone using the completions directly since they'll be expecting exact matches to have a space appended, so in that sense this is a backwards compatibility break. If you'd prefer, we could make this opt-in for now.

**Comment by evanunderscore** [comment]
I've updated this to account for the testing changes. In my opinion, merging this would require a major version bump since some code may rely on the trailing space that is being removed (assuming you're doing semver). Alternatively I could make it optional and have the bash scripts activate this change through an environment variable or some other mechanism.

**Comment by evanunderscore** [comment]
On reflection I think it's a better idea to make this optional. I'll make the appropriate changes.

**Comment by evanunderscore** [comment]
I've updated this so that the default remains unchanged and environments that are prepared to handle this for themselves can opt out. This is ready for another review.

**Comment by kislyuk** [comment]
Looks good. Merging.

I'll play around with this and once I understand the implications (or lack thereof), I'll put my opinion here on whether it should be on by default.

**Pull request merged**
