### PR TITLE
Fix handling of COMP_POINT

### LINKED ISSUE #228: Not work with unicode as input
Example code as below:
```python
def MyCompleter(prefix, **kwargs):
    results = ['aaa', 'bbb']
    return (c for c in results if c.startswith(prefix))

if __name__ == '__main__':
    import argparse
    import argcomplete

    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='command')
    create_parser = subparsers.add_parser('new')
    create_parser.add_argument('title')
    create_parser.add_argument('category').completer = MyCompleter
    argcomplete.autocomplete(parser)
    args = parser.parse_args()
    print args
```

It works as expect when all the inputs are normal characters (assume above code are wrapped in command `demo`):
```bash
$ ./demo.py new 'hi'
--help  -h      aaa     bbb  
```
When the input contains unicode, the auto completer is not working:
```bash
$ ./demo.py new '你好'
```

So, is this a bug or something related to the shell?
I'm using zsh and argcomplete (Version: 1.9.2).

### PR DESCRIPTION
**Pull request by evanunderscore**
Fixes #228

### CODE REVIEW

**Comment by evanunderscore** [comment]
@kislyuk Can I get you to review this please? The code to adjust COMP_POINT has been in there for quite some time, so I want to make sure I'm not missing something important.

**Comment by kislyuk** [comment]
Tested on Python 2 and 3, appears to be correct.

**Comment by kislyuk** [comment]
I'm having difficulty following the details of this behavior on Python 2. On 3, there is no question that it is correct. On 2, I thought the reindexing of comp_point to go from byte coordinates to char coordinates was necessary, but it appears that it's not needed.

**Comment by kislyuk** [comment]
Released in v1.9.3.

**Comment by evanunderscore** [comment]
@kislyuk Thanks for reviewing. As I understand it, it's actually irrelevant whether you're using Python 2 or 3, since Bash determines the value of COMP_POINT by itself based on whatever encoding you're using for your shell. If you set _ARC_DEBUG you can see that COMP_POINT is the same either way, and always corresponds to the length of COMP_LINE in unicode characters.

As I mentioned in the issue, the Bash documentation says COMP_POINT is equal to `${#COMP_LINE}` when you are at the end of the line, and you can test that this works in unicode characters:

```
$ line='prog point test'
$ echo "${#line}"
15
$ line='prog point 你好嘚瑟 '
$ echo "${#line}"
15
```

Based on this, using `ensure_str(os.environ['COMP_LINE'])` seems like it's enough to make everything work as expected.

**Comment by kislyuk** [comment]
Here is why I'm confused:
```
akislyuk@galactica:~/projects/argcomplete>export X=你好嘚瑟; python2 -c'import os; print(len(os.environ["X"]))'
12
akislyuk@galactica:~/projects/argcomplete>export X=你好嘚瑟; python2 -c'import os; print(len(os.environ["X"].decode("utf-8")))'
4
akislyuk@galactica:~/projects/argcomplete>export X=你好嘚瑟; python3 -c'import os; print(len(os.environ["X"]))'
4
```

On Python 3, os.environ contents are automatically decoded for you. If you look at our code, we pass the contents of os.environ["COMP_LINE"] to split_line and then to shlex with no other processing. That means on Python 2, COMP_POINT is being used to index into a bytestring, and on 3, into a unicode string. I'm confused about how that works on Python 2 with wide chars.

**Comment by kislyuk** [comment]
Never mind, I totally missed the part where we run ensure_str. Now it all makes sense.

At some point I must have added ensure_str without thinking about the COMP_POINT reindexing logic (which I should have removed at the same time). So now that's fixed. Thank you.

**Comment by evanunderscore** [comment]
No problem, thanks again for the review.

**Pull request merged**
