### PR TITLE
Add tests for tcsh

### PR DESCRIPTION
**Pull request by evanunderscore**

### CODE REVIEW

**Comment by kislyuk** [comment]
Thanks for the work done here, but I dislike the complexity this design adds to the test suite. Would it be possible to avoid altering the existing test runner, and provide a tcsh mix-in test class that would overload a method? Then we could trigger this mix-in with an environment variable, and specify which tests tcsh is expected to fail with `@unittest.skipIf("TEST_TCSH" in os.environ)` type decorators.

**Comment by evanunderscore** [comment]
I'm not sure I understand exactly what you mean. Do you only expect to use one shell per test run? Would you set Travis to run the tests twice with different environment variables?

**Comment by kislyuk** [comment]
I would run the test suite twice. Right now travis.yml reads:
```
script:
  - make lint
  - coverage run --source=argcomplete ./test/test.py
```
Instead we could change it to:
```
script:
  - make lint
  - coverage run --source=argcomplete ./test/test.py
  - TEST_TCSH=1 coverage run --source=argcomplete ./test/test.py
```

**Comment by kislyuk** [comment]
I would also welcome any other way of organizing the tests that keeps
things as simple as they currently are for bash and sequesters tcsh
specific code into its own class.

**Comment by evanunderscore** [comment]
The problem with that is that it doesn't necessarily make sense to use the original test class as a base for new ones. For example, there are currently tests marked as expected failures for bash that pass in tcsh.

If they are all combined into one class, the expected failure logic could look like:

```
class TestBash(unittest.TestCase):
    @expectedFailureShell('bash')
    def test_foo(self):
        ...
    @expectedFailureShell('tcsh')
    def test_bar(self):
        ...
```

Where `expectedFailureShell` is some decorator we would write. I'd prefer not to use `skipIf` since that skips the test entirely, instead of running it and checking it fails.

**Comment by evanunderscore** [comment]
@kislyuk I've taken some time to reflect on this, and I remain convinced that there is no way to leave the bash tests as they are while using them as a base for the tcsh tests. Conceptually, bash tests are shell tests, tcsh tests are shell tests, but tcsh tests are not necessarily bash tests (though the only difference currently is which ones are expected to fail). However I understand that distinction may not actually matter in a pragmatic sense, and code clarity is important.

If you would like to make a final decision on how you want the tests to be structured, I'll make any necessary changes so we can get this merged.

**Comment by kislyuk** [comment]
If you're convinced there's no way to restructure the code for clarity, I'm fine with what is here now. It would be great if it were simpler, but what we have is not bad.

Merging, thanks again for your work.

**Comment by evanunderscore** [comment]
Thanks. I'll keep thinking about it in the background and open another PR if I can come up with something better.

**Comment by kislyuk** [comment]
I'm running tests on master on my machine (OS X with Homebrew) and getting the following:
```
python test/test.py -v
test_action_activation (__main__.TestArgcomplete) ... ok
test_action_activation_with_subparser (__main__.TestArgcomplete) ... ok
test_basic_completion (__main__.TestArgcomplete) ... ok
test_choices (__main__.TestArgcomplete) ... ok
test_completers (__main__.TestArgcomplete) ... ok
test_custom_validator (__main__.TestArgcomplete) ... ok
test_different_validators (__main__.TestArgcomplete) ... ok
test_directory_completion (__main__.TestArgcomplete) ... ok
test_display_completions (__main__.TestArgcomplete) ... ok
test_exclusive (__main__.TestArgcomplete) ... ok
test_file_completion (__main__.TestArgcomplete) ... ok
test_filescompleter_filetype_integration (__main__.TestArgcomplete) ... ok
test_mixed_optional_positional (__main__.TestArgcomplete) ... ok
test_nargs_one_or_more (__main__.TestArgcomplete) ... ok
test_nargs_optional (__main__.TestArgcomplete) ... ok
test_nargs_zero_or_more (__main__.TestArgcomplete) ... ok
test_non_ascii (__main__.TestArgcomplete) ... ok
test_non_str_choices (__main__.TestArgcomplete) ... ok
test_optional_long_short_filtering (__main__.TestArgcomplete) ... ok
test_optional_nargs (__main__.TestArgcomplete) ... ok
test_positional_remainder (__main__.TestArgcomplete) ... ok
test_readline_entry_point (__main__.TestArgcomplete) ... ok
test_skipped_completer (__main__.TestArgcomplete) ... ok
test_subparser_completers (__main__.TestArgcomplete) ... ok
test_subparsers (__main__.TestArgcomplete) ... ok
test_suppress_args (__main__.TestArgcomplete) ... ok
test_repl_multiple_complete (__main__.TestArgcompleteREPL) ... ok
test_repl_parse_after_complete (__main__.TestArgcompleteREPL) ... usage: test.py [-h] --foo FOO {bar}
test.py: error: too few arguments
usage: test.py [-h] --foo FOO {bar}
test.py: error: argument --foo is required
ok
test_repl_reuse_parser_with_positional (__main__.TestArgcompleteREPL) ... ok
test_repl_subcommand (__main__.TestArgcompleteREPL) ... ok
test_repl_subparser_parse_after_complete (__main__.TestArgcompleteREPL) ... usage: test.py foo [-h] {bar}
test.py foo: error: too few arguments
ok
test_continuation (__main__.TestBash) ... FAIL
test_double_quoted_completion (__main__.TestBash) ... ok
test_exclamation_in_double_quotes (__main__.TestBash) ... expected failure
test_parse_special_characters (__main__.TestBash) ... ok
test_parse_special_characters_dollar (__main__.TestBash) ... expected failure
test_partial_completion (__main__.TestBash) ... ok
test_quoted_exact (__main__.TestBash) ... expected failure
test_quoted_space (__main__.TestBash) ... ok
test_simple_completion (__main__.TestBash) ... ok
test_single_quoted_completion (__main__.TestBash) ... ok
test_single_quotes_in_double_quotes (__main__.TestBash) ... ok
test_single_quotes_in_single_quotes (__main__.TestBash) ... expected failure
test_special_characters (__main__.TestBash) ... ok
test_special_characters_double_quoted (__main__.TestBash) ... ok
test_special_characters_single_quoted (__main__.TestBash) ... ok
test_unquoted_space (__main__.TestBash) ... ok
test_escaped_special (__main__.TestSplitLine) ... ok
test_escaped_special_in_double_quotes (__main__.TestSplitLine) ... expected failure
test_simple (__main__.TestSplitLine) ... ok
test_unescaped_special (__main__.TestSplitLine) ... expected failure
test_continuation (__main__.TestTcsh) ... expected failure
ERROR
test_double_quoted_completion (__main__.TestTcsh) ... ERROR
test_exclamation_in_double_quotes (__main__.TestTcsh) ... expected failure
ERROR
test_parse_special_characters (__main__.TestTcsh) ... expected failure
ERROR
test_parse_special_characters_dollar (__main__.TestTcsh) ... expected failure
ERROR
test_partial_completion (__main__.TestTcsh) ... ERROR
test_quoted_exact (__main__.TestTcsh) ... ERROR
test_quoted_space (__main__.TestTcsh) ... expected failure
ERROR
test_simple_completion (__main__.TestTcsh) ... ERROR
test_single_quoted_completion (__main__.TestTcsh) ... ERROR
test_single_quotes_in_double_quotes (__main__.TestTcsh) ... ERROR
test_single_quotes_in_single_quotes (__main__.TestTcsh) ... ERROR
test_special_characters (__main__.TestTcsh) ... expected failure
ERROR
test_special_characters_double_quoted (__main__.TestTcsh) ... expected failure
ERROR
test_special_characters_single_quoted (__main__.TestTcsh) ... expected failure
ERROR
test_unquoted_space (__main__.TestTcsh) ... expected failure
ERROR

======================================================================
ERROR: test_continuation (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_double_quoted_completion (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_exclamation_in_double_quotes (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_parse_special_characters (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_parse_special_characters_dollar (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 797, in tearDown
    self.sh.run_command('')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_partial_completion (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_quoted_exact (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 797, in tearDown
    self.sh.run_command('')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_quoted_space (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_simple_completion (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_single_quoted_completion (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_single_quotes_in_double_quotes (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_single_quotes_in_single_quotes (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_special_characters (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_special_characters_double_quoted (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_special_characters_single_quoted (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
ERROR: test_unquoted_space (__main__.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 795, in tearDown
    self.sh.run_command('exit')
  File "test/test.py", line 919, in run_command
    self.child.sendline('\x03')
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 538, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 529, in send
    return os.write(self.child_fd, b)
OSError: [Errno 5] Input/output error

======================================================================
FAIL: test_continuation (__main__.TestBash)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 821, in test_continuation
    self.assertEqual(self.sh.run_command('prog cont f\t--'), 'foo=--\r\n')
AssertionError: u'f--\r\n' != u'foo=--\r\n'
- f--
+ foo=--
?  +++


----------------------------------------------------------------------
Ran 67 tests in 31.558s

FAILED (failures=1, errors=16, expected failures=15)
make: *** [test] Error 1
```

**Comment by kislyuk** [comment]
I'm not entirely sure what's going on, any ideas?

**Comment by kislyuk** [comment]
```
>tcsh --version
tcsh 6.18.01 (Astron) 2012-02-14 (x86_64-apple-darwin) options wide,nls,dl,al,kan,sm,rh,color,filec
```

**Comment by evanunderscore** [comment]
All of the tcsh failures seem to be happening after `exit` is run, when it is trying to send Ctrl+C. The wrapper for tcsh is substantially less robust than the bash one provided by pexpect, so this might come down to slight differences in OS X, or the version of tcsh.

I'm slightly more concerned about the bash failure - that result looks like pushing tab did nothing. You can manually adjust your path, source the completion script and try to complete `prog` to see what's going wrong there.

I will try to look at this more closely next week. Let me know if you work anything out in the meantime.

**Comment by evanunderscore** [comment]
If you suppress that error in by changing line 795 do you still get the bash error?

```
try:
    self.sh.run_command('exit')
except OSError:
    pass
```

**Pull request merged**
