### PR TITLE
Attempt to fix failing test in Python 2.7

### PR DESCRIPTION
**Pull request by ulken**

### CODE REVIEW

**Comment by ulken** [comment]
@kislyuk I haven't tested this locally. CI isn't run on PRs, no? I'm on a Mac and Homebrew doesn't support 2.x anymore. Do you mind testing it out?

**Comment by kislyuk** [comment]
Sorry about the delay. CI should run on pull requests now. Please rebase and we'll check if this fixes the test suite.

**Comment by ulken** [comment]
@kislyuk Done. It passes on Linux. As far as I can tell, the reason it's failing on Mac is unrelated to this PR. It's more about 2.7 being deprecated and changes to `pip`.

**Comment by evanunderscore** [comment]
The OSX tests are failing because [this fix](https://github.com/kislyuk/argcomplete/commit/4c5958bd442fe5a3deca8d7f6f1085c00464c1c5) wasn't included in the port to GitHub actions. You are correct that it's unrelated to this PR.

**Comment by kislyuk** [comment]
Sorry I don't know how that happened, I'll re-add the fix to GHA

**Comment by ulken** [comment]
Alright, let me know when to do a new rebase.

**Comment by ulken** [comment]
Good to go?

**Comment by kislyuk** [comment]
@ulken your fix works, thanks for the contribution.

@evanunderscore I have re-added the fix but those other OS X tests are still failing. I am going to disable the tests in question on OS X until we can find a solution that works with the latest pip.

**Comment by evanunderscore** [comment]
For whatever reason, `pip` on the runner is still getting the latest version even though the install step downgrades it. I was only using that particular feature of pip to work around an issue specific to Homebrew, but that workaround no longer works with the latest pip. In order to fix the test it would probably have to be rewritten to use virtual environments. I'm not likely to have time to look at it soon so disabling the tests is fine.

**Pull request merged**
