### PR TITLE
Support PowerShell

### PR DESCRIPTION
**Pull request by bebound**
Reopen #392 and fix the README.rst

### CODE REVIEW

**Comment by bebound** [comment]
There are still some errors, I'll fix them.

**Comment by kislyuk** [comment]
Thank you

**Comment by kislyuk** [comment]
@bebound can you please update this so that the file `register-python-argcomplete.cmd` does not get installed on non-Windows platforms by default?

**Comment by kislyuk** [comment]
I have deleted the file `scripts/register-python-argcomplete.cmd` and will not be adding it back. In general, scripts for contributor-supported shells will need to be installed by separate means activated via setuptools extras.

**Comment by bebound** [comment]
Windows user cannot run `register-python-argcomplete` without this cmd file.

**Comment by kislyuk** [comment]
I understand. We need to find a way to only install this file on Windows.

**Comment by bebound** [comment]
How about using `entry_points`? https://github.com/bebound/argcomplete/tree/entry-point
It works on Linux and Windows. I don't know if it is compatible with tch.

**Pull request merged**
