### PR TITLE
Flake8/pep8 fixes

### PR DESCRIPTION
**Pull request by Grokzen**
Hi.

I ran all python code through the flake8 tool and i fixed most of the issues it complained about. I ran the same command as i added in the Makefile.

Most things is simple spaces or new lines to make the code easier to read.

### CODE REVIEW

**Comment by kislyuk** [comment]
Please remove the following files from your changeset:

* argcomplete/my_shlex.py
* docs/conf.py
* docs/examples/describe_github_user.py

**Comment by Grokzen** [comment]
@kislyuk Hi. I have rebased this PR ontop of master again to fix the merge conflicts. Do you still want me to remove some files from this changeset on reasons other then merge conflict? I could see a reason for conf.py but the other 2 files O.o

**Comment by kislyuk** [comment]
Yes. Please remove the files I listed. The shlex file is a copy of upstream shlex with minimal modifications. The file `docs/examples/describe_github_user.py` is optimized for brevity so the fixes don't work for it either.

Thanks.

**Comment by Grokzen** [comment]
@kislyuk Code is rewritten to not include the files you commented on. I also squashed them into 1 commit and rebased them ontop of the latest master commit. I also added the files to flake8 exclude so that they will not pop up in the future when running that command :]

**Comment by kislyuk** [comment]
Thanks.

**Pull request merged**
