### PR TITLE
Complete python -m module

### LINKED ISSUE #173: Support for python -m module
Is it possible for argcomplete to work for modules run as `python -m module`? This is necessary to do once you start organizing your code in a module (rather than just a single script) to make relative imports work correctly, but I don't really want to make a separate entry point script if I don't have to. 

I am using global completion and it isn't working, at least not out of the box.

### PR DESCRIPTION
**Pull request by evanunderscore**
Fixes #173

### CODE REVIEW

**Comment by kislyuk** [comment]
LGTM although the "_scripts" subdirectory seems superfluous, you could just put the script at package top level.

**Comment by asmeurer** [comment]
I tried testing this and it didn't work. I checked out your branch and ran

```
export PYTHONPATH=~/Documents/argcomplete/
```

and completions did not work for `python -m mymodule`.

**Comment by asmeurer** [comment]
Oh nevermind, I forgot to resource the completion script. 

It seems to work. Would be possible to complete the module names after `-m` as well?

**Comment by kislyuk** [comment]
I dislike this feature creep. What you describe is a job for a dedicated python completer.

**Comment by evanunderscore** [comment]
I would like it to be able to complete module names, but that could be difficult, and probably doesn't belong in this PR.

I've removed the `_scripts` directory. I'll merge this in.

**Comment by kislyuk** [comment]
Great, thanks.

Module completions seem to be available upstream as of https://github.com/scop/bash-completion/commit/0e8d34e, which is from 2013 and says it's available in 2.1. I have bash-completion-1.3_1 installed though, and `python -m<TAB>` doesn't seem to be working. Is this an upstream bug?

**Comment by kislyuk** [comment]
D'oh, of course, 1.3 is older than 2.1. It looks like Homebrew's version is way out of date.

Looking at http://packages.ubuntu.com/search?keywords=bash-completion, 2.1 is available as of Ubuntu 14.04+. But on my 16.04 instance, `python -m<TAB>` doesn't seem to be working either.

**Comment by kislyuk** [comment]
OK, it works if I do `source /usr/share/bash-completion/completions/python`. So it looks like you have to turn it on manually by running `ln -s /usr/share/bash-completion/completions/python /etc/bash_completion.d` or something.

**Comment by evanunderscore** [comment]
I have 2.1 but no python in the completions folder, so I'm not sure what that's about. The default completion function is supposed to source that file for you the first time you attempt to complete `python`. If you have the argcomplete's global completion installed, it's going to steal completion away for python before it gets to that.

**Comment by evanunderscore** [comment]
I've created #207 to capture the problem of global completion not interacting with bash-completion.

**Pull request merged**
