### PR TITLE
mypy: Basic typings

### LINKED ISSUE #396: Support mypy type annotations aka PEP 484
Currently when using `mypy` as a static type checker you must add this project to the ignore list.

The message looks a bit like this:

```
Run python -m mypy <module>
<module>/cli.py:35: error: Skipping analyzing "argcomplete": module is installed, but missing library stubs or py.typed marker  [import]
```

More information on how to add this to a project and fix the warning can be found [here](https://mypy.readthedocs.io/en/stable/).

### PR DESCRIPTION
**Pull request by tony**
Fixes #396

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@tony Anything one can do to help you get this ready to be merged and afterwards merged? I would be interested in this.

**Comment by tony** [comment]
@SchoolGuy I just need more time 🙏 

@kislyuk There seems to be more interest in mypy than just me.  I will continue this over the next few weeks

**Comment by tony** [comment]
@kislyuk This is mypy w/ default settings. It should be fine to merge as-is. What do you think?  

I will make a second PR based on this with full typings.

cc: @SchoolGuy The PR with annotations won't be until the follow up PR.

**Comment by kislyuk** [comment]
Thanks, LGTM

**Pull request merged**
